[build]
  publish = "."
  # ビルドコマンドが必要な場合は以下を追加
  # command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "01push/netlify/functions"
